#!/bin/ansible-playbook
# code: language=ansible
- name: Create a VM with Docker and Jenkins in Docker for Project 11
  hosts: b11
  become: yes
  roles:
  - docker

  tasks:
  - name: Adding user in docker group
    ansible.builtin.user:
      name: "{{ ansible_user }}"
      groups: "docker"
      append: true

  - name: Creating docker network
    community.docker.docker_network:
      name: jenkins

  - name: Creating and/or starting dind container
    community.docker.docker_container:
      name: jenkins-docker
      image: docker:dind
      detach: true
      privileged: true
      restart_policy: "on-failure"
      networks:
        - name: jenkins
          aliases: docker
      published_ports:
        - 2376:2376
      env:
        DOCKER_TLS_CERTDIR: /certs
      # volume_driver: overlay2
      volumes:
        - jenkins-docker-certs:/certs/client
        - jenkins-data:/var/jenkins_home

  - name: Upload Dockerfile for building Jenkins container
    ansible.builtin.copy:
      dest: ./Dockerfile
      src: ../b11_dockerfile

  - name: Building a Jenkins image
    ansible.builtin.docker_image:
      name: myjenkins-blueocean
      tag: "2.473-1"
      path: "."
      state: present

  - name: Creating and/or starting Jenkins container
    community.docker.docker_container:
      name: jenkins-blueocean
      image: myjenkins-blueocean:2.473-1
      detach: true
      restart_policy: "on-failure"
      networks:
        - name: jenkins
      published_ports:
        - 8080:8080
        - 50000:50000
      env:
        DOCKER_HOST: "tcp://docker:2376"
        DOCKER_CERT_PATH: "/certs/client"
        DOCKER_TLS_VERIFY: "1"
      volumes:
        - jenkins-data:/var/jenkins_home
        - jenkins-docker-certs:/certs/client:ro

  # - name: Printing initialAdminPassword
  #   ansible.builtin.command: docker exec jenkins-blueocean cat /var/jenkins_home/secrets/initialAdminPassword